### ISSUE TITLE
pivot functions

### ISSUE THREAD

**Issue by AnnaK42** [LSC-MEM-course/simple-regressions-assignment-1-AnnaK42#1]
So I'm doing the 2nd assignment, but my pivot_wider function still doesn't work (still doesn't seem to exist), even after updating the packages with the line you told me to put in from last time. RStudio is definitely up-to-date. 

I have tidyverse and tidyr installed and used library(tidyverse) and library(dplyr) and everything.

**Comment by shoestringpsycholing** [comment]
Hmm.  Well, pivot_wider() is actually from the tidyr package.  After loading tidyverse, can you run this line:

sessionInfo()

You should see (among other stuff):

R version 3.6.1
tidyr_1.0.0

If if you see those but the command `?pivot_wider` tells you there's no such function, copy & paste the whole output of `sessionInfo()`

**Comment by scottrjackson** [comment]
Hmm. Well, pivot_wider() is actually from the tidyr package. After loading tidyverse, can you run this line:

sessionInfo()

You should see (among other stuff):

R version 3.6.1
tidyr_1.0.0

If if you see those but the command `?pivot_wider` tells you there's no such function, copy & paste the whole output of `sessionInfo()`

**Comment by AnnaK42** [comment]
crap, it's R version 3.5.1

I'm using Anaconda (to run python stuff too) so that's probably why. I'll try to update it. Just found out that gather and spread works at least too.

**Comment by scottrjackson** [comment]
:-)

Yep, gather and spread work great.  I literally just started using the pivot functions when writing this assignment, when it was pointed out that they're the latest and greatest.

I do agree with the rationale for switching yet again (I used melt and cast/dcast for many years before gather and spread came along), in terms of the pivot arguments being a bit more intuitive and easy to remember, but do what works for you!
